# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 930e8928425a4993987112010fb71f505f5d2ee13c0c4815eb0cd6586669f78c2b373a36fcd1bc803ade40522ec89b33b74f8e33871607cc31b9cd274e93f034

test:
  secret_key_base: d1981c2197035c95aea8468e16b07ec7ea5f6dac503d8c79b565463e58df5e2f9e7d25713adad724981a2febce2b7e78194ef093cabec78ea6200ea4a0fc05ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
